### PR TITLE
fixed admin side bar icon

### LINKED ISSUE #271: [AP] Create error UI popups for login page

### LINKED ISSUE #275: [AP] Add Admin Portal Sidebar Icon

### LINKED ISSUE #286: [UA] Error display upon user signup/login

### PR DESCRIPTION
**Pull request by hyang14**
image

### CODE REVIEW

File: Admin-Portal/src/pages/Auth/Login.tsx [hunk 1]
```diff
@@ -19,6 +19,42 @@ const schema = Yup.object().shape({
...
+
+const SuccessMessage: React.FC<SuccessMessageProps> = ({
+  success,
+  setSuccess,
+}) => {
+  const handleClose = () => {
+    setSuccess(null);
+  };
+  return (
+    <Snackbar
```
Comment (OliviaLiu417) [inline Admin-Portal/src/pages/Auth/Login.tsx]: There should be an existing success message component, you can just reuse that

**Review by OliviaLiu417 — CHANGES_REQUESTED** [review]

File: Admin-Portal/src/pages/Auth/Login.tsx (hunk 1 above)
Comment (hyang14) [reply Admin-Portal/src/pages/Auth/Login.tsx]: Yea, I saw that one, but it seems like that only takes in a boolean value. Since I want to tell the user that they should check their email, should just modify that one to make it have the extra option to take in a string value as well?

**Review by OliviaLiu417 — APPROVED** [review]
